<a href="https://colab.research.google.com/github/pasin2545/Challenge_loop_if_basicmath/blob/master/CE_DA_Pandas_2022s1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('hello')

hello


In [2]:
1+1

2

## Lib

In [3]:
import numpy as np
import pandas as pd

## Basic Numpy

In [4]:
[1,2,3] + [10,10,10]


[1, 2, 3, 10, 10, 10]

In [5]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
np.array([1,2,3]) + np.array([10,10,10])

array([11, 12, 13])

In [7]:
np.array([1,2,3])*3

array([3, 6, 9])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(5,10,2)

array([5, 7, 9])

In [11]:
np.random.rand(5)

array([0.2837536 , 0.46809319, 0.08515335, 0.06573034, 0.71357383])

In [15]:
np.random.randint(10,20,5)

array([10, 12, 17, 15, 19])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones(5)*7

array([7., 7., 7., 7., 7.])

In [19]:
x = np.arange(5)

In [20]:
x

array([0, 1, 2, 3, 4])

In [21]:
x.sum()

10

In [22]:
np.sum(x)

10

In [24]:
np.mean(x)

2.0

In [30]:
x.min()

0

In [29]:
x.max()

4

In [28]:
x.std()

1.4142135623730951

In [31]:
x = np.arange(5)*10

In [32]:
x

array([ 0, 10, 20, 30, 40])

In [33]:
x[2]

20

In [34]:
x[0:3]

array([ 0, 10, 20])

In [35]:
x[1:3]

array([10, 20])

In [36]:
x[:3]

array([ 0, 10, 20])

In [37]:
x[3:]

array([30, 40])

In [38]:
x

array([ 0, 10, 20, 30, 40])

In [39]:
x[-1]

40

In [40]:
x[-2]

30